### ISSUE TITLE
Error by calculating AutoText.AUTOTEXT_PAGE_X_OF_Y

### ISSUE THREAD

**Issue by buedi** [intive-FDV/DynamicJasper#98]
After updating to DynamicJasper v5.3.1 together witch jasperreports v6.13.0+ we getting an exaction by calculating the "AUTOTEXT_PAGE_X_OF_Y"

...
final AutoText autoTextPage = new AutoText(**AutoText.AUTOTEXT_PAGE_X_OF_Y**, AutoText.POSITION_FOOTER, HorizontalBandAlignment.RIGHT);
      dynamicReportBuilder.addAutoText(autoTextPage);
...

at runtime I getting the error:

[JavaFX Application Thread] ERROR c.m.r.s.i.JasperReportsServiceImpl - Error during printDynamicReport...
net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expressions class file:
1. The operator + is undefined for the argument type(s) Integer, int
                value = ""+" " + (((java.lang.Integer)variable_PAGE_NUMBER.getValue())+0)+" " + ""; //$JR_EXPR_ID=53$
                                 <------------------------------------------------------>
2. The operator + is undefined for the argument type(s) Integer, int
                value = str("autotext.page")+" " + (((java.lang.Integer)variable_PAGE_NUMBER.getValue())+0)+" " + str("autotext.of"); //$JR_EXPR_ID=54$
                                                   <------------------------------------------------------>
3. The operator + is undefined for the argument type(s) Integer, int
                value = ""+" " + (((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+0)+" " + ""; //$JR_EXPR_ID=53$
                                 <--------------------------------------------------------->
4. The operator + is undefined for the argument type(s) Integer, int
                value = str("autotext.page")+" " + (((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+0)+" " + str("autotext.of"); //$JR_EXPR_ID=54$
                                                   <--------------------------------------------------------->
5. The operator + is undefined for the argument type(s) Integer, int
                value = ""+" " + (((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+0)+" " + ""; //$JR_EXPR_ID=53$
                                 <--------------------------------------------------------------->
6. The operator + is undefined for the argument type(s) Integer, int
                value = str("autotext.page")+" " + (((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+0)+" " + str("autotext.of"); //$JR_EXPR_ID=54$
                                                   <--------------------------------------------------------------->
6 errors
.
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:229)
	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:358)
	at net.sf.jasperreports.engine.JasperCompileManager.compileReport(JasperCompileManager.java:618)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperReport(DynamicJasperHelper.java:539)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperReport(DynamicJasperHelper.java:506)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperPrint(DynamicJasperHelper.java:243)
	at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperPrint(DynamicJasperHelper.java:215)

**Comment by aakupcov** [comment]
Actually non of the AUTOTEXT_PAGE works!
